config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/home' => 'pages#home'          # app home page
  get '/userhome' => 'pages#userhome'  # users' home page
  get '/user/:id' => 'pages#userhome'  # each user's home page
  get '/members' => 'pages#members'    # list of members
  get '/help' => 'pages#help'          # help pages
  get '/about' => 'pages#about'        # project info
  get '/posts/tag/:name' => 'posts#tags' # find tagged posts
  # get '/users/sign_out' => 'pages#home'
  resources :posts, only: [:create]

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tags
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 30 }
  validates :taglist, length: { maximum: 30 }
  validate :one_post_per_day

  before_create :set_date_today

  after_create do
  	post = Post.find_by(id: self.id)
  	btags = post.taglist.strip.split(/\s+/)
  	btags.uniq.map do |atag|
  		tag = Tag.find_or_create_by(name: atag)
  		post.tags << tag
  	end
  end

  private
  	def set_date_today
  		self.thedate = Date.current
  	end

  	def one_post_per_day
  		if (! user.posts.empty?) && user.posts.first.thedate == Date.current
  			errors.add(:thedate, "You can post only once per day")
  		end
  	end
end

app/models/tag.rb
class Tag < ApplicationRecord
	# tags a/several posts
	has_and_belongs_to_many :posts
	# order alphabetically
	default_scope -> { order(name: :asc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, length: { maximum: 30 }

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # strong parameters check if using devise
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  	def configure_permitted_parameters
  		# new hash elements that can be passed as params
  		devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  		devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  		devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.all
    @tags = Tag.all
    @post = current_user.posts.build if user_signed_in?
  end

  def userhome
    @tags = Tag.all
    if (User.find_by_username(params[:id]))
      @username = params[:id]
      the_user = User.find_by_username(params[:id])
      @posts = the_user.posts
      if user_signed_in? && @username == current_user.username
        @post = current_user.posts.build
      end
    else
      redirect_to root_path, notice: "User not found."
    end
  end

  def help
  end

  def about
  end

  def members
    @users = User.all
  end

    private
    # maybe not needed
    def post_params
      params.require(:post).permit(:title, :body, :taglist)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
  	@post = current_user.posts.build(post_params)
 	respond_to do |f|
  		if (@post.save)
  			f.html { redirect_to root_url, notice: "Post saved"}
  		else
  			messages = ""
  			@post.errors.full_messages.each do |message|
  				messages += message
  			end
  			f.html { redirect_to root_url, notice: "Errors in post: #{messages}" }
  		end
  	end
  end

  def tags
  	tag = Tag.find_by(name: params[:name])
  	@posts = tag.posts
  end

  private
  	def post_params
  		params.require(:post).permit(:title, :body, :taglist)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
	def render_tags_as_links(taglist)
		taglist.gsub(/\w+/){|t| link_to t, "/posts/tag/#{t}"}.html_safe
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-inverse navbar-fixed-bottom">
  <div class="container-fluid">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  	<%= render 'layouts/navbar_user' %>
<% else %>
  	<%= render 'layouts/navbar_guest' %>
<% end %>

app/views/layouts/_navbar_guest.html.erb
<!-- navbar for user not logged in -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Today...</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Members", members_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#">Sign in</a></li>
      <li><a href="#">Sign up</a></li>
    </ul>
  </div>
</nav>

app/views/layouts/_navbar_user.html.erb
<!-- navbar for user not logged in -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Today...</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Members", members_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/user/<%= current_user.username %>"><%= current_user.username %> Home</a></li>
      <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Today</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/_all_tags.html.erb
<% @tags.each do |t| %>
   <div class="atag-link">
       <%= render_tags_as_links(t.name) %>
   </div>
<% end %>

app/views/pages/about.html.erb
<h1>About Today...</h1>
<p>Developed by <a href="mailto:grantrmalcolm@gmail.com">Grant Malcolm</a>
for <a href="yozu.co.uk">Yozu</a>.</p>

app/views/pages/help.html.erb
<h1>Today I have... Help</h1>
<p>
<strong>Today</strong> helps you keep track of your daily activities,
and the activities of other Today members.
Find out who these members are by clicking on <strong>Members</strong> at the top of the page.
</p>
<p>
See their activities by clicking on their names in the list.
</p>
<p>
Clicking on <%= link_to "Today...", root_url %> shows you everyone&rsquo;s posts;
clicking on <%= link_to "Members", members_path %> shows you all members -
you can click on a member&rsquo;s name to see all their posts.
</p>
<p>
If you sign up, you have your own home page where you can see your posts
and add a post (at most one per day).
</p>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'shared/today_logo' %>
  </div>
  <div class="col-md-6">
    <h3>Who's doing what</h3>
    <% if user_signed_in? %>
      <%= render partial: 'shared/post_form', locals: {thetags: @tags} %>
    <% end %>
    <% if @posts.empty? %>
      No posts yet.
    <% else %>
      <%= render partial: 'shared/post_list' %>
    <% end %>
  </div>
  <div class="col-md-3">
    <h3>Tags</h3><h4>what we're about</h4>
    <%= render partial: 'all_tags', locals: {thetags: @tags} %>
  </div>  
</div>

app/views/pages/members.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'shared/today_logo' %>
  </div>
  <div class="col-md-6">
    <h3>Members</h3><h4>who we are</h4>
    <% @users.each do |member| %>
      <div class="panel panel-default">
         <div class="panel-body">
           <span class="member-username">
           <a href="/user/<%= member.username %>">
             <strong><%= member.username %></strong>
           </a>
           </span>
           <span class="member-join-date">
           	 Joined: <%= member.created_at.to_date %>
           </span>
           <span class="member-num-posts">
             <%= member.posts.size %> Posts
           </span>
         </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <h3>Tags</h3><h4>what we're about</h4>
  </div>  
</div>

app/views/pages/userhome.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'shared/today_logo' %>
    <% if user_signed_in? && current_user.username == @username %>
      <h3>My to-do list</h3>
    <% end %>
  </div>
  <div class="col-md-6">
    <% if user_signed_in? && current_user.username == @username %>
      <h3>My Posts</h3>
      <span id="notice"><%= notice %></span>
      <%= render partial: 'shared/post_form', locals: {thetags: @tags} %>
    <% else %>
      <h3><%= @username %>&rsquo;s posts</h3>
    <% end %>
    <% if @posts.empty? %>
       No posts yet.
    <% else %>
      <%= render partial: 'shared/post_list', locals: {theposts: @posts} %>
    <% end %>
  </div>
  <div class="col-md-3">
    <h3>Tags</h3><h4>what we're about</h4>
    <%= render partial: 'all_tags', locals: {thetags: @tags} %>
  </div>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/tags.html.erb
<% @posts.each do |post| %>
   <div class="panel panel-default">
   <div class="panel-heading">
        <%= post.user.username %> has:
        <%= post.title %>
    </div>
    <div class="panel-body">
        <%= post.body %>
    </div>
    <div class="panel-footer">
        Tags: <%= render_tags_as_links(post.taglist) %>
    </div>
    </div>
<% end %>

app/views/shared/_post_form.html.erb
<p>Tell us what you&rsquo;ve done today:</p>
<%= form_for(@post) do |form| %>
   <span id="notice"><%= notice %></span>
   <div class="field">
   	 <%= form.text_field :title, id: :post_title, placeholder: "Title: Today I have...", autofocus: true %>
   </div>

  <div class="field">
    <%= form.text_area :body, id: :post_body, placeholder: "Give some details..." %>
  </div>

  <div class="field">
    Add your own tags or choose from: 
    <select onchange="swap(this.value, 'post_taglist')">
      <option disabled selected value> -- choose tags-- </option>
      <% @tags.each do |tag| %>
        <option value="<%= tag.name %>"><%= tag.name %></option>
      <% end %>
    </select>
    <%= form.text_field :taglist, id: :post_taglist %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shared/_post_list.html.erb
<% the_date = Date.current %>
      <% if @posts.first.thedate == the_date %>
        <div class="post-date">
          Today
        </div>
      <% else %>
        <% the_date = @posts.first.thedate %>
        <div class="post-date">
           <%= the_date %>
        </div>
      <% end %>
      <% @posts.each do |post| %>
        <% if post.thedate != the_date %>
           <% the_date = post.thedate %>
           <div class="post-date">
              <%= the_date %>
           </div>          
        <% end %>
        <div class="panel panel-default">
        <div class="panel-heading">
           <%= post.user.username %> has:
           <%= post.title %>
        </div>
        <div class="panel-body">
           <%= post.body %>
        </div>
        <div class="panel-footer">
           Tags: <%= render_tags_as_links(post.taglist) %>
        </div>
        </div>
      <% end %>

app/views/shared/_today_logo.html.erb
<div class="center jumbotron">
  <h3>Today I have...</h3>
  <div class="today-tagline">
    kept in touch with who's doing what
  </div>
</div>